<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="LibraDex.Harness\**\*.cs" />
    <Compile Remove="LibraDex.FileSearch\**\*.cs" />
    <Compile Remove="LibraDex.FileSearch.Runner\**\*.cs" />
    <Compile Remove="LibraDex.ShapeBench\**\*.cs" />
  </ItemGroup>

</Project>
