using System.Reflection;
using System.Text;
using LibraDex;

internal static partial class RawHarness
{
    private const string DefaultPublicApiSnapshotPath = "docs/public-api-snapshot.txt";

    private static int RunPublicApiSnapshot(string[] args)
    {
        if (typeof(LibraDexConditionOperator<>).GetMethod("All", BindingFlags.Public | BindingFlags.Instance) is not null)
            throw new InvalidOperationException("The developer-facing condition grammar must not expose All(); unfiltered result selection is implicit.");

        string path = GetOption(args, "--path", DefaultPublicApiSnapshotPath);
        bool update = HasOption(args, "--update");
        string snapshot = BuildPublicApiSnapshot(typeof(Catalog).Assembly);

        if (update)
        {
            string? directory = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(path, NormalizeSnapshotText(snapshot), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            Console.WriteLine($"public-api-snapshot updated {path}");
            return 0;
        }

        if (!File.Exists(path))
        {
            Console.Error.WriteLine($"public-api-snapshot baseline missing: {path}");
            Console.Error.WriteLine("Run with --update after reviewing the current public surface.");
            return 1;
        }

        string expected = File.ReadAllText(path, Encoding.UTF8);
        if (NormalizeSnapshotText(expected).Equals(NormalizeSnapshotText(snapshot), StringComparison.Ordinal))
        {
            Console.WriteLine($"public-api-snapshot ok {path}");
            return 0;
        }

        string actualPath = Path.Combine("artifacts", "public-api-snapshot-current.txt");
        Directory.CreateDirectory("artifacts");
        File.WriteAllText(actualPath, snapshot, Encoding.UTF8);
        Console.Error.WriteLine("public-api-snapshot mismatch");
        Console.Error.WriteLine($"expected: {path}");
        Console.Error.WriteLine($"actual:   {actualPath}");
        Console.Error.WriteLine("Review the diff, then run with --update only if the public API change is intentional.");
        return 1;
    }

    private static string NormalizeSnapshotText(string text)
    {
        return text.Replace("\r\n", "\n", StringComparison.Ordinal).TrimEnd() + "\n";
    }

    private static string BuildPublicApiSnapshot(Assembly assembly)
    {
        Type[] types = assembly.GetExportedTypes()
            .OrderBy(type => type.FullName, StringComparer.Ordinal)
            .ToArray();

        StringBuilder builder = new();
        builder.AppendLine("# LibraDex Public API Snapshot");
        builder.AppendLine("# Generated by: dotnet run --project LibraDex.Harness\\LibraDex.Harness.csproj -c Release -- public-api-snapshot --update");
        builder.AppendLine("# Review changes before updating this file.");
        builder.AppendLine();
        builder.AppendLine($"Assembly: {assembly.GetName().Name}");
        builder.AppendLine($"ExportedTypes: {types.Length}");
        builder.AppendLine();

        for (int i = 0; i < types.Length; i++)
        {
            Type type = types[i];
            AppendType(builder, type);
            AppendConstructors(builder, type);
            AppendFields(builder, type);
            AppendProperties(builder, type);
            AppendEvents(builder, type);
            AppendMethods(builder, type);
            builder.AppendLine();
        }

        return builder.ToString();
    }

    private static void AppendType(StringBuilder builder, Type type)
    {
        builder.Append("type ");
        builder.Append(GetTypeKind(type));
        builder.Append(' ');
        builder.Append(GetFriendlyTypeName(type));
        builder.AppendLine();
    }

    private static void AppendConstructors(StringBuilder builder, Type type)
    {
        ConstructorInfo[] constructors = type.GetConstructors(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
            .OrderBy(FormatConstructor, StringComparer.Ordinal)
            .ToArray();

        for (int i = 0; i < constructors.Length; i++)
        {
            builder.Append("  ctor ");
            builder.AppendLine(FormatConstructor(constructors[i]));
        }
    }

    private static void AppendFields(StringBuilder builder, Type type)
    {
        FieldInfo[] fields = type.GetFields(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
            .Where(field => !field.IsSpecialName)
            .OrderBy(field => field.Name, StringComparer.Ordinal)
            .ToArray();

        for (int i = 0; i < fields.Length; i++)
        {
            FieldInfo field = fields[i];
            builder.Append("  field ");
            builder.Append(field.IsStatic ? "static " : string.Empty);
            builder.Append(GetFriendlyTypeName(field.FieldType));
            builder.Append(' ');
            builder.AppendLine(field.Name);
        }
    }

    private static void AppendProperties(StringBuilder builder, Type type)
    {
        PropertyInfo[] properties = type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
            .OrderBy(property => property.Name, StringComparer.Ordinal)
            .ToArray();

        for (int i = 0; i < properties.Length; i++)
        {
            PropertyInfo property = properties[i];
            builder.Append("  property ");
            MethodInfo? getter = property.GetMethod;
            MethodInfo? setter = property.SetMethod;
            if ((getter?.IsStatic ?? false) || (setter?.IsStatic ?? false))
            {
                builder.Append("static ");
            }

            builder.Append(GetFriendlyTypeName(property.PropertyType));
            builder.Append(' ');
            builder.Append(property.Name);
            builder.Append(" {");
            if (getter is not null)
            {
                builder.Append("get;");
            }

            if (setter is not null)
            {
                builder.Append("set;");
            }

            builder.AppendLine("}");
        }
    }

    private static void AppendEvents(StringBuilder builder, Type type)
    {
        EventInfo[] events = type.GetEvents(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
            .OrderBy(candidate => candidate.Name, StringComparer.Ordinal)
            .ToArray();

        for (int i = 0; i < events.Length; i++)
        {
            EventInfo candidate = events[i];
            builder.Append("  event ");
            builder.Append(GetFriendlyTypeName(candidate.EventHandlerType ?? typeof(object)));
            builder.Append(' ');
            builder.AppendLine(candidate.Name);
        }
    }

    private static void AppendMethods(StringBuilder builder, Type type)
    {
        MethodInfo[] methods = type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
            .Where(method => !method.IsSpecialName)
            .OrderBy(FormatMethod, StringComparer.Ordinal)
            .ToArray();

        for (int i = 0; i < methods.Length; i++)
        {
            builder.Append("  method ");
            builder.AppendLine(FormatMethod(methods[i]));
        }
    }

    private static string FormatConstructor(ConstructorInfo constructor)
    {
        return $"({FormatParameters(constructor.GetParameters())})";
    }

    private static string FormatMethod(MethodInfo method)
    {
        StringBuilder builder = new();
        if (method.IsStatic)
        {
            builder.Append("static ");
        }

        builder.Append(GetFriendlyTypeName(method.ReturnType));
        builder.Append(' ');
        builder.Append(method.Name);
        if (method.IsGenericMethodDefinition)
        {
            builder.Append('<');
            Type[] args = method.GetGenericArguments();
            for (int i = 0; i < args.Length; i++)
            {
                if (i > 0)
                {
                    builder.Append(',');
                }

                builder.Append(args[i].Name);
            }

            builder.Append('>');
        }

        builder.Append('(');
        builder.Append(FormatParameters(method.GetParameters()));
        builder.Append(')');
        return builder.ToString();
    }

    private static string FormatParameters(ParameterInfo[] parameters)
    {
        StringBuilder builder = new();
        for (int i = 0; i < parameters.Length; i++)
        {
            if (i > 0)
            {
                builder.Append(", ");
            }

            ParameterInfo parameter = parameters[i];
            if (parameter.IsOut)
            {
                builder.Append("out ");
            }
            else if (parameter.ParameterType.IsByRef)
            {
                builder.Append("ref ");
            }

            Type parameterType = parameter.ParameterType.IsByRef
                ? parameter.ParameterType.GetElementType() ?? parameter.ParameterType
                : parameter.ParameterType;

            builder.Append(GetFriendlyTypeName(parameterType));
            builder.Append(' ');
            builder.Append(parameter.Name);
            if (parameter.HasDefaultValue)
            {
                builder.Append(" = ");
                builder.Append(FormatDefaultValue(parameter.DefaultValue));
            }
        }

        return builder.ToString();
    }

    private static string FormatDefaultValue(object? value)
    {
        return value switch
        {
            null => "null",
            string text => "\"" + text.Replace("\"", "\\\"", StringComparison.Ordinal) + "\"",
            bool flag => flag ? "true" : "false",
            Enum enumValue => enumValue.GetType().Name + "." + enumValue,
            _ => Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture) ?? "null"
        };
    }

    private static string GetTypeKind(Type type)
    {
        if (type.IsEnum)
        {
            return "enum";
        }

        if (type.IsInterface)
        {
            return "interface";
        }

        if (type.IsValueType)
        {
            return "struct";
        }

        if (type.IsClass && type.IsAbstract && type.IsSealed)
        {
            return "static-class";
        }

        return type.IsClass ? "class" : "type";
    }

    private static string GetFriendlyTypeName(Type type)
    {
        if (type.IsGenericParameter)
        {
            return type.Name;
        }

        if (type.IsArray)
        {
            return GetFriendlyTypeName(type.GetElementType() ?? typeof(object)) + "[]";
        }

        if (type.IsByRef)
        {
            return GetFriendlyTypeName(type.GetElementType() ?? typeof(object)) + "&";
        }

        if (type.IsPointer)
        {
            return GetFriendlyTypeName(type.GetElementType() ?? typeof(object)) + "*";
        }

        Type nullable = Nullable.GetUnderlyingType(type) ?? type;
        string suffix = nullable == type ? string.Empty : "?";

        if (nullable.IsGenericType)
        {
            string name = GetNonGenericTypeName(nullable);
            int tick = name.IndexOf('`', StringComparison.Ordinal);
            if (tick >= 0)
            {
                name = name[..tick];
            }

            Type[] args = nullable.GetGenericArguments();
            return name + "<" + string.Join(",", args.Select(GetFriendlyTypeName)) + ">" + suffix;
        }

        return GetNonGenericTypeName(nullable) + suffix;
    }

    private static string GetNonGenericTypeName(Type type)
    {
        if (type.FullName is not null)
        {
            return type.FullName;
        }

        return string.IsNullOrEmpty(type.Namespace)
            ? type.Name
            : type.Namespace + "." + type.Name;
    }
}
